title: SLTzone
description: my simple blog

# Server
destination:      _gh_pages
baseurl:          /
url:              http://babakslt.github.io
encoding:         UTF-8

paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about.html
 - title: Contact
   url: /contact.html

social:
   github: babakslt
   twitter: theslt
   facebook: babakslt
   email: babakslt@gmail.com



